//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ__SCHEDULES
    {
        public System.Guid OID { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public string DURATION { get; set; }
        public string NEXT_TIME { get; set; }
        public string LATENCY { get; set; }
        public Nullable<System.DateTime> LAST_TIME { get; set; }
        public Nullable<decimal> JOBNO { get; set; }
    }
}
