//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ__QUEUES
    {
        public System.Guid OID { get; set; }
        public decimal EVENTID { get; set; }
        public string NAME { get; set; }
        public decimal TABLE_OBJNO { get; set; }
        public decimal USAGE { get; set; }
        public decimal ENABLE_FLAG { get; set; }
        public Nullable<decimal> MAX_RETRIES { get; set; }
        public Nullable<decimal> RETRY_DELAY { get; set; }
        public Nullable<decimal> PROPERTIES { get; set; }
        public Nullable<decimal> RET_TIME { get; set; }
        public string QUEUE_COMMENT { get; set; }
        public Nullable<decimal> MEMORY_THRESHOLD { get; set; }
        public string SERVICE_NAME { get; set; }
        public string NETWORK_NAME { get; set; }
    }
}
