//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ__INTERNET_AGENTS
    {
        public AQ__INTERNET_AGENTS()
        {
            this.AQ__INTERNET_AGENT_PRIVS = new HashSet<AQ__INTERNET_AGENT_PRIVS>();
        }
    
        public string AGENT_NAME { get; set; }
        public decimal PROTOCOL { get; set; }
        public string SPARE1 { get; set; }
    
        public virtual ICollection<AQ__INTERNET_AGENT_PRIVS> AQ__INTERNET_AGENT_PRIVS { get; set; }
    }
}
