//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ__QUEUE_TABLES
    {
        public string SCHEMA { get; set; }
        public string NAME { get; set; }
        public decimal UDATA_TYPE { get; set; }
        public decimal OBJNO { get; set; }
        public decimal FLAGS { get; set; }
        public decimal SORT_COLS { get; set; }
        public string TIMEZONE { get; set; }
        public string TABLE_COMMENT { get; set; }
    }
}
