//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOODREQUESTOR
    {
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONENUMBER { get; set; }
        public string BLOODGROUP { get; set; }
        public decimal USERID { get; set; }
        public string EMAIL { get; set; }
        public string MESSAGE { get; set; }
    }
}
