//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF__PUSHED_TRANSACTIONS
    {
        public decimal SOURCE_SITE_ID { get; set; }
        public Nullable<decimal> LAST_TRAN_ID { get; set; }
        public string DISABLED { get; set; }
        public string SOURCE_SITE { get; set; }
    }
}
