//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF__LOB
    {
        public System.Guid ID { get; set; }
        public string ENQ_TID { get; set; }
        public byte[] BLOB_COL { get; set; }
        public string CLOB_COL { get; set; }
        public string NCLOB_COL { get; set; }
    }
}
