//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF__ERROR
    {
        public string ENQ_TID { get; set; }
        public string ORIGIN_TRAN_DB { get; set; }
        public string ORIGIN_ENQ_TID { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<decimal> STEP_NO { get; set; }
        public Nullable<decimal> RECEIVER { get; set; }
        public Nullable<System.DateTime> ENQ_TIME { get; set; }
        public Nullable<decimal> ERROR_NUMBER { get; set; }
        public string ERROR_MSG { get; set; }
    }
}
