//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF__DESTINATION
    {
        public DEF__DESTINATION()
        {
            this.DEF__CALLDEST = new HashSet<DEF__CALLDEST>();
            this.REPCAT__REPSCHEMA = new HashSet<REPCAT__REPSCHEMA>();
        }
    
        public string DBLINK { get; set; }
        public decimal LAST_DELIVERED { get; set; }
        public string LAST_ENQ_TID { get; set; }
        public Nullable<decimal> LAST_SEQ { get; set; }
        public string DISABLED { get; set; }
        public Nullable<decimal> JOB { get; set; }
        public Nullable<decimal> LAST_TXN_COUNT { get; set; }
        public Nullable<decimal> LAST_ERROR_NUMBER { get; set; }
        public string LAST_ERROR_MESSAGE { get; set; }
        public string APPLY_INIT { get; set; }
        public System.Guid CATCHUP { get; set; }
        public string ALTERNATE { get; set; }
        public Nullable<decimal> TOTAL_TXN_COUNT { get; set; }
        public Nullable<decimal> TOTAL_PROP_TIME_THROUGHPUT { get; set; }
        public Nullable<decimal> TOTAL_PROP_TIME_LATENCY { get; set; }
        public Nullable<decimal> TO_COMMUNICATION_SIZE { get; set; }
        public Nullable<decimal> FROM_COMMUNICATION_SIZE { get; set; }
        public byte[] FLAG { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<decimal> SPARE4 { get; set; }
    
        public virtual ICollection<DEF__CALLDEST> DEF__CALLDEST { get; set; }
        public virtual ICollection<REPCAT__REPSCHEMA> REPCAT__REPSCHEMA { get; set; }
    }
}
