//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF__CALLDEST
    {
        public string ENQ_TID { get; set; }
        public decimal STEP_NO { get; set; }
        public string DBLINK { get; set; }
        public string SCHEMA_NAME { get; set; }
        public string PACKAGE_NAME { get; set; }
        public Nullable<System.Guid> CATCHUP { get; set; }
    
        public virtual DEF__DESTINATION DEF__DESTINATION { get; set; }
    }
}
