//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNRC_GSBA
    {
        public decimal LOGMNR_UID { get; set; }
        public decimal AS_OF_SCN { get; set; }
        public Nullable<decimal> FDO_LENGTH { get; set; }
        public byte[] FDO_VALUE { get; set; }
        public Nullable<decimal> CHARSETID { get; set; }
        public Nullable<decimal> NCHARSETID { get; set; }
        public Nullable<decimal> DBTIMEZONE_LEN { get; set; }
        public string DBTIMEZONE_VALUE { get; set; }
        public Nullable<decimal> LOGMNR_SPARE1 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE2 { get; set; }
        public string LOGMNR_SPARE3 { get; set; }
        public Nullable<System.DateTime> LOGMNR_SPARE4 { get; set; }
    }
}
