//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_OBJ_
    {
        public Nullable<decimal> OBJV_ { get; set; }
        public Nullable<decimal> OWNER_ { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> NAMESPACE { get; set; }
        public string SUBNAME { get; set; }
        public Nullable<decimal> TYPE_ { get; set; }
        public Nullable<System.Guid> OID_ { get; set; }
        public string REMOTEOWNER { get; set; }
        public string LINKNAME { get; set; }
        public Nullable<decimal> FLAGS { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<System.DateTime> STIME { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
        public Nullable<decimal> START_SCNBAS { get; set; }
        public Nullable<decimal> START_SCNWRP { get; set; }
    }
}
