//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_CDEF_
    {
        public decimal CON_ { get; set; }
        public Nullable<decimal> COLS { get; set; }
        public Nullable<decimal> TYPE_ { get; set; }
        public Nullable<decimal> ROBJ_ { get; set; }
        public Nullable<decimal> RCON_ { get; set; }
        public Nullable<decimal> ENABLED { get; set; }
        public Nullable<decimal> DEFER { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
