//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNRT_MDDL_
    {
        public decimal SOURCE_OBJ_ { get; set; }
        public string SOURCE_ROWID { get; set; }
        public string DEST_ROWID { get; set; }
    }
}
