//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_ENC_
    {
        public decimal OBJ_ { get; set; }
        public decimal OWNER_ { get; set; }
        public Nullable<decimal> ENCALG { get; set; }
        public Nullable<decimal> INTALG { get; set; }
        public byte[] COLKLC { get; set; }
        public Nullable<decimal> KLCLEN { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string MKEYID { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
