//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_LOGMNR_BUILDLOG
    {
        public string BUILD_DATE { get; set; }
        public Nullable<decimal> DB_TXN_SCNBAS { get; set; }
        public Nullable<decimal> DB_TXN_SCNWRP { get; set; }
        public Nullable<decimal> CURRENT_BUILD_STATE { get; set; }
        public Nullable<decimal> COMPLETION_STATUS { get; set; }
        public Nullable<decimal> MARKED_LOG_FILE_LOW_SCN { get; set; }
        public string INITIAL_XID { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
