//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_PARTOBJ_
    {
        public Nullable<decimal> PARTTYPE { get; set; }
        public Nullable<decimal> PARTCNT { get; set; }
        public Nullable<decimal> PARTKEYCOLS { get; set; }
        public Nullable<decimal> FLAGS { get; set; }
        public Nullable<decimal> DEFTS_ { get; set; }
        public Nullable<decimal> DEFPCTFREE { get; set; }
        public Nullable<decimal> DEFPCTUSED { get; set; }
        public Nullable<decimal> DEFPCTTHRES { get; set; }
        public Nullable<decimal> DEFINITRANS { get; set; }
        public Nullable<decimal> DEFMAXTRANS { get; set; }
        public Nullable<decimal> DEFTINIEXTS { get; set; }
        public Nullable<decimal> DEFEXTSIZE { get; set; }
        public Nullable<decimal> DEFMINEXTS { get; set; }
        public Nullable<decimal> DEFMAXEXTS { get; set; }
        public Nullable<decimal> DEFEXTPCT { get; set; }
        public Nullable<decimal> DEFLISTS { get; set; }
        public Nullable<decimal> DEFGROUPS { get; set; }
        public Nullable<decimal> DEFLOGGING { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<decimal> DEFINCLCOL { get; set; }
        public string PARAMETERS { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
