//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_COL_
    {
        public Nullable<decimal> COL_ { get; set; }
        public Nullable<decimal> SEGCOL_ { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> TYPE_ { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> PRECISION_ { get; set; }
        public Nullable<decimal> SCALE { get; set; }
        public Nullable<decimal> NULL_ { get; set; }
        public decimal INTCOL_ { get; set; }
        public Nullable<decimal> PROPERTY { get; set; }
        public Nullable<decimal> CHARSETID { get; set; }
        public Nullable<decimal> CHARSETFORM { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
