//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_PROCESSED_LOG_
    {
        public decimal SESSION_ { get; set; }
        public decimal THREAD_ { get; set; }
        public Nullable<decimal> SEQUENCE_ { get; set; }
        public Nullable<decimal> FIRST_CHANGE_ { get; set; }
        public Nullable<decimal> NEXT_CHANGE_ { get; set; }
        public Nullable<System.DateTime> FIRST_TIME { get; set; }
        public Nullable<System.DateTime> NEXT_TIME { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string INFO { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
