//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_SUBCOLTYPE_
    {
        public decimal INTCOL_ { get; set; }
        public System.Guid TOID { get; set; }
        public decimal VERSION_ { get; set; }
        public Nullable<decimal> INTCOLS { get; set; }
        public byte[] INTCOL_S { get; set; }
        public Nullable<decimal> FLAGS { get; set; }
        public Nullable<decimal> SYNOBJ_ { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
