//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_SESSION_
    {
        public decimal SESSION_ { get; set; }
        public Nullable<decimal> CLIENT_ { get; set; }
        public string SESSION_NAME { get; set; }
        public Nullable<decimal> DB_ID { get; set; }
        public Nullable<decimal> RESETLOGS_CHANGE_ { get; set; }
        public Nullable<decimal> SESSION_ATTR { get; set; }
        public string SESSION_ATTR_VERBOSE { get; set; }
        public Nullable<decimal> START_SCN { get; set; }
        public Nullable<decimal> END_SCN { get; set; }
        public Nullable<decimal> SPILL_SCN { get; set; }
        public Nullable<System.DateTime> SPILL_TIME { get; set; }
        public Nullable<decimal> OLDEST_SCN { get; set; }
        public Nullable<decimal> RESUME_SCN { get; set; }
        public string GLOBAL_DB_NAME { get; set; }
        public Nullable<decimal> RESET_TIMESTAMP { get; set; }
        public Nullable<decimal> BRANCH_SCN { get; set; }
        public string VERSION { get; set; }
        public string REDO_COMPAT { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<decimal> SPARE4 { get; set; }
        public Nullable<decimal> SPARE5 { get; set; }
        public Nullable<System.DateTime> SPARE6 { get; set; }
        public string SPARE7 { get; set; }
        public string SPARE8 { get; set; }
    }
}
