//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_RESTART_CKPT_TXINFO_
    {
        public decimal SESSION_ { get; set; }
        public decimal XIDUSN { get; set; }
        public decimal XIDSLT { get; set; }
        public decimal XIDSQN { get; set; }
        public decimal SESSION_NUM { get; set; }
        public decimal SERIAL_NUM { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public Nullable<decimal> START_SCN { get; set; }
        public decimal EFFECTIVE_SCN { get; set; }
        public Nullable<decimal> OFFSET { get; set; }
        public byte[] TX_DATA { get; set; }
    }
}
