//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_SEED_
    {
        public Nullable<decimal> SEED_VERSION { get; set; }
        public Nullable<decimal> GATHER_VERSION { get; set; }
        public string SCHEMANAME { get; set; }
        public decimal OBJ_ { get; set; }
        public Nullable<decimal> OBJV_ { get; set; }
        public string TABLE_NAME { get; set; }
        public string COL_NAME { get; set; }
        public Nullable<decimal> COL_ { get; set; }
        public decimal INTCOL_ { get; set; }
        public Nullable<decimal> SEGCOL_ { get; set; }
        public Nullable<decimal> TYPE_ { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> PRECISION_ { get; set; }
        public Nullable<decimal> SCALE { get; set; }
        public decimal NULL_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
