//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNRC_GTCS
    {
        public decimal LOGMNR_UID { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal OBJV_ { get; set; }
        public decimal SEGCOL_ { get; set; }
        public decimal INTCOL_ { get; set; }
        public string COLNAME { get; set; }
        public decimal TYPE_ { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> PRECISION { get; set; }
        public Nullable<decimal> SCALE { get; set; }
        public Nullable<decimal> INTERVAL_LEADING_PRECISION { get; set; }
        public Nullable<decimal> INTERVAL_TRAILING_PRECISION { get; set; }
        public Nullable<decimal> PROPERTY { get; set; }
        public Nullable<System.Guid> TOID { get; set; }
        public Nullable<decimal> CHARSETID { get; set; }
        public Nullable<decimal> CHARSETFORM { get; set; }
        public string TYPENAME { get; set; }
        public string FQCOLNAME { get; set; }
        public Nullable<decimal> NUMINTCOLS { get; set; }
        public Nullable<decimal> NUMATTRS { get; set; }
        public Nullable<decimal> ADTORDER { get; set; }
        public Nullable<decimal> LOGMNR_SPARE1 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE2 { get; set; }
        public string LOGMNR_SPARE3 { get; set; }
        public Nullable<System.DateTime> LOGMNR_SPARE4 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE5 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE6 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE7 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE8 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE9 { get; set; }
        public Nullable<decimal> COL_ { get; set; }
        public string XTYPESCHEMANAME { get; set; }
        public string XTYPENAME { get; set; }
        public string XFQCOLNAME { get; set; }
        public Nullable<decimal> XTOPINTCOL { get; set; }
        public Nullable<decimal> XREFFEDTABLEOBJN { get; set; }
        public Nullable<decimal> XREFFEDTABLEOBJV { get; set; }
        public Nullable<decimal> XCOLTYPEFLAGS { get; set; }
        public Nullable<decimal> XOPQTYPETYPE { get; set; }
        public Nullable<decimal> XOPQTYPEFLAGS { get; set; }
        public Nullable<decimal> XOPQLOBINTCOL { get; set; }
        public Nullable<decimal> XOPQOBJINTCOL { get; set; }
        public Nullable<decimal> XXMLINTCOL { get; set; }
        public Nullable<decimal> EAOWNER_ { get; set; }
        public string EAMKEYID { get; set; }
        public Nullable<decimal> EAENCALG { get; set; }
        public Nullable<decimal> EAINTALG { get; set; }
        public byte[] EACOLKLC { get; set; }
        public Nullable<decimal> EAKLCLEN { get; set; }
        public Nullable<decimal> EAFLAGS { get; set; }
    }
}
