//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_ATTRIBUTE_
    {
        public decimal VERSION_ { get; set; }
        public string NAME { get; set; }
        public decimal ATTRIBUTE_ { get; set; }
        public Nullable<System.Guid> ATTR_TOID { get; set; }
        public Nullable<decimal> ATTR_VERSION_ { get; set; }
        public Nullable<decimal> SYNOBJ_ { get; set; }
        public Nullable<decimal> PROPERTIES { get; set; }
        public Nullable<decimal> CHARSETID { get; set; }
        public Nullable<decimal> CHARSETFORM { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> PRECISION_ { get; set; }
        public Nullable<decimal> SCALE { get; set; }
        public string EXTERNNAME { get; set; }
        public Nullable<decimal> XFLAGS { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<decimal> SPARE4 { get; set; }
        public Nullable<decimal> SPARE5 { get; set; }
        public Nullable<decimal> SETTER { get; set; }
        public Nullable<decimal> GETTER { get; set; }
        public System.Guid TOID { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
