//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_TAB_
    {
        public Nullable<decimal> TS_ { get; set; }
        public Nullable<decimal> COLS { get; set; }
        public Nullable<decimal> PROPERTY { get; set; }
        public Nullable<decimal> INTCOLS { get; set; }
        public Nullable<decimal> KERNELCOLS { get; set; }
        public Nullable<decimal> BOBJ_ { get; set; }
        public Nullable<decimal> TRIGFLAG { get; set; }
        public Nullable<decimal> FLAGS { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
