//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNRC_GSII
    {
        public decimal LOGMNR_UID { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal BO_ { get; set; }
        public decimal INDTYPE_ { get; set; }
        public Nullable<decimal> DROP_SCN { get; set; }
        public Nullable<decimal> LOGMNR_SPARE1 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE2 { get; set; }
        public string LOGMNR_SPARE3 { get; set; }
        public Nullable<System.DateTime> LOGMNR_SPARE4 { get; set; }
    }
}
