//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_SESSION_EVOLVE_
    {
        public Nullable<decimal> BRANCH_LEVEL { get; set; }
        public decimal SESSION_ { get; set; }
        public decimal DB_ID { get; set; }
        public decimal RESET_SCN { get; set; }
        public decimal RESET_TIMESTAMP { get; set; }
        public Nullable<decimal> PREV_RESET_SCN { get; set; }
        public Nullable<decimal> PREV_RESET_TIMESTAMP { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<System.DateTime> SPARE4 { get; set; }
    }
}
