//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_DICTSTATE_
    {
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> START_SCNBAS { get; set; }
        public Nullable<decimal> START_SCNWRP { get; set; }
        public Nullable<decimal> END_SCNBAS { get; set; }
        public Nullable<decimal> END_SCNWRP { get; set; }
        public Nullable<decimal> REDO_THREAD { get; set; }
        public Nullable<decimal> RBASQN { get; set; }
        public Nullable<decimal> RBABLK { get; set; }
        public Nullable<decimal> RBABYTE { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
