//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_CCOL_
    {
        public decimal CON_ { get; set; }
        public Nullable<decimal> OBJ_ { get; set; }
        public Nullable<decimal> COL_ { get; set; }
        public Nullable<decimal> POS_ { get; set; }
        public decimal INTCOL_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
