//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_TYPE_
    {
        public decimal VERSION_ { get; set; }
        public string VERSION { get; set; }
        public Nullable<System.Guid> TVOID { get; set; }
        public Nullable<decimal> TYPECODE { get; set; }
        public Nullable<decimal> PROPERTIES { get; set; }
        public Nullable<decimal> ATTRIBUTES { get; set; }
        public Nullable<decimal> METHODS { get; set; }
        public Nullable<decimal> HIDDENMETHODS { get; set; }
        public Nullable<decimal> SUPERTYPES { get; set; }
        public Nullable<decimal> SUBTYPES { get; set; }
        public Nullable<decimal> EXTERNTYPE { get; set; }
        public string EXTERNNAME { get; set; }
        public string HELPERCLASSNAME { get; set; }
        public Nullable<decimal> LOCAL_ATTRS { get; set; }
        public Nullable<decimal> LOCAL_METHODS { get; set; }
        public Nullable<System.Guid> TYPEID { get; set; }
        public Nullable<System.Guid> ROOTTOID { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<System.Guid> SUPERTOID { get; set; }
        public byte[] HASHCODE { get; set; }
        public System.Guid TOID { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
