//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_SPILL_
    {
        public decimal SESSION_ { get; set; }
        public decimal XIDUSN { get; set; }
        public decimal XIDSLT { get; set; }
        public decimal XIDSQN { get; set; }
        public decimal CHUNK { get; set; }
        public decimal STARTIDX { get; set; }
        public decimal ENDIDX { get; set; }
        public decimal FLAG { get; set; }
        public decimal SEQUENCE_ { get; set; }
        public byte[] SPILL_DATA { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
    }
}
