//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNRP_CTAS_PART_MAP
    {
        public decimal LOGMNR_UID { get; set; }
        public decimal BASEOBJ_ { get; set; }
        public decimal BASEOBJV_ { get; set; }
        public decimal KEYOBJ_ { get; set; }
        public decimal PART_ { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public string SPARE3 { get; set; }
    }
}
