//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_OPQTYPE_
    {
        public decimal INTCOL_ { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> FLAGS { get; set; }
        public Nullable<decimal> LOBCOL { get; set; }
        public Nullable<decimal> OBJCOL { get; set; }
        public Nullable<decimal> EXTRACOL { get; set; }
        public Nullable<System.Guid> SCHEMAOID { get; set; }
        public Nullable<decimal> ELEMNUM { get; set; }
        public string SCHEMAURL { get; set; }
        public decimal OBJ_ { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
