//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_LOG_
    {
        public decimal SESSION_ { get; set; }
        public decimal THREAD_ { get; set; }
        public decimal SEQUENCE_ { get; set; }
        public decimal FIRST_CHANGE_ { get; set; }
        public Nullable<decimal> NEXT_CHANGE_ { get; set; }
        public Nullable<System.DateTime> FIRST_TIME { get; set; }
        public Nullable<System.DateTime> NEXT_TIME { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string INFO { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string DICT_BEGIN { get; set; }
        public string DICT_END { get; set; }
        public string STATUS_INFO { get; set; }
        public decimal DB_ID { get; set; }
        public decimal RESETLOGS_CHANGE_ { get; set; }
        public decimal RESET_TIMESTAMP { get; set; }
        public Nullable<decimal> PREV_RESETLOGS_CHANGE_ { get; set; }
        public Nullable<decimal> PREV_RESET_TIMESTAMP { get; set; }
        public Nullable<decimal> BLOCKS { get; set; }
        public Nullable<decimal> BLOCK_SIZE { get; set; }
        public Nullable<decimal> FLAGS { get; set; }
        public Nullable<decimal> CONTENTS { get; set; }
        public Nullable<decimal> RECID { get; set; }
        public Nullable<decimal> RECSTAMP { get; set; }
        public Nullable<decimal> MARK_DELETE_TIMESTAMP { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
        public Nullable<decimal> SPARE4 { get; set; }
        public Nullable<decimal> SPARE5 { get; set; }
    }
}
