//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_SESSION_ACTIONS_
    {
        public Nullable<decimal> FLAGSRUNTIME { get; set; }
        public Nullable<decimal> DROPSCN { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<System.DateTime> DISPATCHTIME { get; set; }
        public Nullable<System.DateTime> DROPTIME { get; set; }
        public Nullable<decimal> LCRCOUNT { get; set; }
        public string ACTIONNAME { get; set; }
        public decimal LOGMNRSESSION_ { get; set; }
        public decimal PROCESSROLE_ { get; set; }
        public decimal ACTIONTYPE_ { get; set; }
        public Nullable<decimal> FLAGSDEFINETIME { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> XIDUSN { get; set; }
        public Nullable<decimal> XIDSLT { get; set; }
        public Nullable<decimal> XIDSQN { get; set; }
        public Nullable<decimal> THREAD_ { get; set; }
        public Nullable<decimal> STARTSCN { get; set; }
        public Nullable<decimal> STARTSUBSCN { get; set; }
        public Nullable<decimal> ENDSCN { get; set; }
        public Nullable<decimal> ENDSUBSCN { get; set; }
        public Nullable<decimal> RBASQN { get; set; }
        public Nullable<decimal> RBABLK { get; set; }
        public Nullable<decimal> RBABYTE { get; set; }
        public Nullable<decimal> SESSION_ { get; set; }
        public Nullable<decimal> OBJ_ { get; set; }
        public Nullable<decimal> ATTR1 { get; set; }
        public Nullable<decimal> ATTR2 { get; set; }
        public Nullable<decimal> ATTR3 { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<System.DateTime> SPARE3 { get; set; }
        public string SPARE4 { get; set; }
    }
}
