//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNRC_GTLO
    {
        public decimal LOGMNR_UID { get; set; }
        public decimal KEYOBJ_ { get; set; }
        public decimal LVLCNT { get; set; }
        public decimal BASEOBJ_ { get; set; }
        public decimal BASEOBJV_ { get; set; }
        public Nullable<decimal> LVL1OBJ_ { get; set; }
        public Nullable<decimal> LVL2OBJ_ { get; set; }
        public decimal LVL0TYPE_ { get; set; }
        public Nullable<decimal> LVL1TYPE_ { get; set; }
        public Nullable<decimal> LVL2TYPE_ { get; set; }
        public Nullable<decimal> OWNER_ { get; set; }
        public string OWNERNAME { get; set; }
        public string LVL0NAME { get; set; }
        public string LVL1NAME { get; set; }
        public string LVL2NAME { get; set; }
        public decimal INTCOLS { get; set; }
        public Nullable<decimal> COLS { get; set; }
        public Nullable<decimal> KERNELCOLS { get; set; }
        public Nullable<decimal> TAB_FLAGS { get; set; }
        public Nullable<decimal> TRIGFLAG { get; set; }
        public Nullable<decimal> ASSOC_ { get; set; }
        public Nullable<decimal> OBJ_FLAGS { get; set; }
        public Nullable<decimal> TS_ { get; set; }
        public string TSNAME { get; set; }
        public Nullable<decimal> PROPERTY { get; set; }
        public decimal START_SCN { get; set; }
        public Nullable<decimal> DROP_SCN { get; set; }
        public Nullable<decimal> XIDUSN { get; set; }
        public Nullable<decimal> XIDSLT { get; set; }
        public Nullable<decimal> XIDSQN { get; set; }
        public Nullable<decimal> FLAGS { get; set; }
        public Nullable<decimal> LOGMNR_SPARE1 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE2 { get; set; }
        public string LOGMNR_SPARE3 { get; set; }
        public Nullable<System.DateTime> LOGMNR_SPARE4 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE5 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE6 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE7 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE8 { get; set; }
        public Nullable<decimal> LOGMNR_SPARE9 { get; set; }
        public Nullable<decimal> PARTTYPE { get; set; }
        public Nullable<decimal> SUBPARTTYPE { get; set; }
        public Nullable<decimal> UNSUPPORTEDCOLS { get; set; }
        public Nullable<decimal> COMPLEXTYPECOLS { get; set; }
        public Nullable<decimal> NTPARENTOBJNUM { get; set; }
        public Nullable<decimal> NTPARENTOBJVERSION { get; set; }
        public Nullable<decimal> NTPARENTINTCOLNUM { get; set; }
        public Nullable<decimal> LOGMNRTLOFLAGS { get; set; }
        public string LOGMNRMCV { get; set; }
    }
}
