//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_PARAMETER_
    {
        public decimal SESSION_ { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> SCN { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public string SPARE3 { get; set; }
    }
}
