//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMNR_DICTIONARY_
    {
        public string DB_NAME { get; set; }
        public Nullable<decimal> DB_ID { get; set; }
        public string DB_CREATED { get; set; }
        public string DB_DICT_CREATED { get; set; }
        public Nullable<decimal> DB_DICT_SCN { get; set; }
        public byte[] DB_THREAD_MAP { get; set; }
        public Nullable<decimal> DB_TXN_SCNBAS { get; set; }
        public Nullable<decimal> DB_TXN_SCNWRP { get; set; }
        public Nullable<decimal> DB_RESETLOGS_CHANGE_ { get; set; }
        public string DB_RESETLOGS_TIME { get; set; }
        public string DB_VERSION_TIME { get; set; }
        public string DB_REDO_TYPE_ID { get; set; }
        public string DB_REDO_RELEASE { get; set; }
        public string DB_CHARACTER_SET { get; set; }
        public string DB_VERSION { get; set; }
        public string DB_STATUS { get; set; }
        public string DB_GLOBAL_NAME { get; set; }
        public Nullable<decimal> DB_DICT_MAXOBJECTS { get; set; }
        public decimal DB_DICT_OBJECTCOUNT { get; set; }
        public decimal LOGMNR_UID { get; set; }
        public Nullable<decimal> LOGMNR_FLAGS { get; set; }
    }
}
