//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGSTDBY_EDS_TABLES
    {
        public string OWNER { get; set; }
        public string TABLE_NAME { get; set; }
        public string SHADOW_TABLE_NAME { get; set; }
        public string BASE_TRIGGER_NAME { get; set; }
        public string SHADOW_TRIGGER_NAME { get; set; }
        public string DBLINK { get; set; }
        public Nullable<decimal> FLAGS { get; set; }
        public string STATE { get; set; }
        public Nullable<decimal> OBJV { get; set; }
        public Nullable<decimal> OBJ_ { get; set; }
        public Nullable<decimal> SOBJ_ { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public string SPARE2 { get; set; }
        public Nullable<decimal> SPARE3 { get; set; }
    }
}
