//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGSTDBY_EVENTS
    {
        public System.DateTime EVENT_TIME { get; set; }
        public Nullable<decimal> CURRENT_SCN { get; set; }
        public Nullable<decimal> COMMIT_SCN { get; set; }
        public Nullable<decimal> XIDUSN { get; set; }
        public Nullable<decimal> XIDSLT { get; set; }
        public Nullable<decimal> XIDSQN { get; set; }
        public Nullable<decimal> ERRVAL { get; set; }
        public string EVENT { get; set; }
        public string FULL_EVENT { get; set; }
        public string ERROR { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public string SPARE3 { get; set; }
    }
}
