//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGSTDBY_APPLY_MILESTONE
    {
        public decimal SESSION_ID { get; set; }
        public decimal COMMIT_SCN { get; set; }
        public Nullable<System.DateTime> COMMIT_TIME { get; set; }
        public decimal SYNCH_SCN { get; set; }
        public decimal EPOCH { get; set; }
        public decimal PROCESSED_SCN { get; set; }
        public Nullable<System.DateTime> PROCESSED_TIME { get; set; }
        public decimal FETCHLWM_SCN { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public string SPARE3 { get; set; }
    }
}
