//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGSTDBY_FLASHBACK_SCN
    {
        public decimal PRIMARY_SCN { get; set; }
        public Nullable<System.DateTime> PRIMARY_TIME { get; set; }
        public Nullable<decimal> STANDBY_SCN { get; set; }
        public Nullable<System.DateTime> STANDBY_TIME { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<System.DateTime> SPARE3 { get; set; }
    }
}
