//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_LOG
    {
        public MVIEW__ADV_LOG()
        {
            this.MVIEW__ADV_AJG = new HashSet<MVIEW__ADV_AJG>();
            this.MVIEW__ADV_CLIQUE = new HashSet<MVIEW__ADV_CLIQUE>();
            this.MVIEW__ADV_ELIGIBLE = new HashSet<MVIEW__ADV_ELIGIBLE>();
            this.MVIEW__ADV_INFO = new HashSet<MVIEW__ADV_INFO>();
            this.MVIEW__ADV_JOURNAL = new HashSet<MVIEW__ADV_JOURNAL>();
            this.MVIEW__ADV_LEVEL = new HashSet<MVIEW__ADV_LEVEL>();
            this.MVIEW__ADV_OUTPUT = new HashSet<MVIEW__ADV_OUTPUT>();
            this.MVIEW__ADV_ROLLUP = new HashSet<MVIEW__ADV_ROLLUP>();
        }
    
        public decimal RUNID_ { get; set; }
        public Nullable<decimal> FILTERID_ { get; set; }
        public Nullable<System.DateTime> RUN_BEGIN { get; set; }
        public Nullable<System.DateTime> RUN_END { get; set; }
        public Nullable<decimal> RUN_TYPE { get; set; }
        public string UNAME { get; set; }
        public decimal STATUS { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<decimal> COMPLETED { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string ERROR_CODE { get; set; }
    
        public virtual ICollection<MVIEW__ADV_AJG> MVIEW__ADV_AJG { get; set; }
        public virtual ICollection<MVIEW__ADV_CLIQUE> MVIEW__ADV_CLIQUE { get; set; }
        public virtual ICollection<MVIEW__ADV_ELIGIBLE> MVIEW__ADV_ELIGIBLE { get; set; }
        public virtual ICollection<MVIEW__ADV_INFO> MVIEW__ADV_INFO { get; set; }
        public virtual ICollection<MVIEW__ADV_JOURNAL> MVIEW__ADV_JOURNAL { get; set; }
        public virtual ICollection<MVIEW__ADV_LEVEL> MVIEW__ADV_LEVEL { get; set; }
        public virtual MVIEW__ADV_FILTERINSTANCE MVIEW__ADV_FILTERINSTANCE { get; set; }
        public virtual ICollection<MVIEW__ADV_OUTPUT> MVIEW__ADV_OUTPUT { get; set; }
        public virtual ICollection<MVIEW__ADV_ROLLUP> MVIEW__ADV_ROLLUP { get; set; }
    }
}
