//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_WORKLOAD
    {
        public MVIEW__ADV_WORKLOAD()
        {
            this.MVIEW__ADV_BASETABLE = new HashSet<MVIEW__ADV_BASETABLE>();
        }
    
        public decimal QUERYID_ { get; set; }
        public decimal COLLECTIONID_ { get; set; }
        public System.DateTime COLLECTTIME { get; set; }
        public string APPLICATION { get; set; }
        public Nullable<decimal> CARDINALITY { get; set; }
        public Nullable<decimal> RESULTSIZE { get; set; }
        public string UNAME { get; set; }
        public Nullable<System.DateTime> QDATE { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public Nullable<decimal> EXEC_TIME { get; set; }
        public string SQL_TEXT { get; set; }
        public decimal SQL_TEXTLEN { get; set; }
        public Nullable<decimal> SQL_HASH { get; set; }
        public Nullable<System.Guid> SQL_ADDR { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
    
        public virtual ICollection<MVIEW__ADV_BASETABLE> MVIEW__ADV_BASETABLE { get; set; }
    }
}
