//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_PARAMETERS
    {
        public string PARAMETER_NAME { get; set; }
        public decimal PARAMETER_TYPE { get; set; }
        public string STRING_VALUE { get; set; }
        public Nullable<System.DateTime> DATE_VALUE { get; set; }
        public Nullable<decimal> NUMERICAL_VALUE { get; set; }
    }
}
