//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_ROLLUP
    {
        public decimal RUNID_ { get; set; }
        public decimal CLEVELID_ { get; set; }
        public decimal PLEVELID_ { get; set; }
        public decimal FLAGS { get; set; }
    
        public virtual MVIEW__ADV_LEVEL MVIEW__ADV_LEVEL { get; set; }
        public virtual MVIEW__ADV_LEVEL MVIEW__ADV_LEVEL1 { get; set; }
        public virtual MVIEW__ADV_LOG MVIEW__ADV_LOG { get; set; }
    }
}
