//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_FJG
    {
        public MVIEW__ADV_FJG()
        {
            this.MVIEW__ADV_GC = new HashSet<MVIEW__ADV_GC>();
        }
    
        public decimal FJGID_ { get; set; }
        public decimal AJGID_ { get; set; }
        public decimal FJGDESLEN { get; set; }
        public byte[] FJGDES { get; set; }
        public decimal HASHVALUE { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
    
        public virtual MVIEW__ADV_AJG MVIEW__ADV_AJG { get; set; }
        public virtual ICollection<MVIEW__ADV_GC> MVIEW__ADV_GC { get; set; }
    }
}
