//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_FILTER
    {
        public decimal FILTERID_ { get; set; }
        public decimal SUBFILTERNUM_ { get; set; }
        public decimal SUBFILTERTYPE { get; set; }
        public string STR_VALUE { get; set; }
        public Nullable<decimal> NUM_VALUE1 { get; set; }
        public Nullable<decimal> NUM_VALUE2 { get; set; }
        public Nullable<System.DateTime> DATE_VALUE1 { get; set; }
        public Nullable<System.DateTime> DATE_VALUE2 { get; set; }
    }
}
