//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_CLIQUE
    {
        public decimal CLIQUEID_ { get; set; }
        public decimal RUNID_ { get; set; }
        public decimal CLIQUEDESLEN { get; set; }
        public byte[] CLIQUEDES { get; set; }
        public decimal HASHVALUE { get; set; }
        public decimal FREQUENCY { get; set; }
        public decimal BYTECOST { get; set; }
        public decimal ROWSIZE { get; set; }
        public decimal NUMROWS { get; set; }
    
        public virtual MVIEW__ADV_LOG MVIEW__ADV_LOG { get; set; }
    }
}
