//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_PARTITION
    {
        public decimal RUNID_ { get; set; }
        public decimal RANK_ { get; set; }
        public string SUMMARY_OWNER { get; set; }
        public string QUERY_TEXT { get; set; }
    }
}
