//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_LEVEL
    {
        public MVIEW__ADV_LEVEL()
        {
            this.MVIEW__ADV_ROLLUP = new HashSet<MVIEW__ADV_ROLLUP>();
            this.MVIEW__ADV_ROLLUP1 = new HashSet<MVIEW__ADV_ROLLUP>();
        }
    
        public decimal RUNID_ { get; set; }
        public decimal LEVELID_ { get; set; }
        public Nullable<decimal> DIMOBJ_ { get; set; }
        public decimal FLAGS { get; set; }
        public decimal TBLOBJ_ { get; set; }
        public byte[] COLUMNLIST { get; set; }
        public string LEVELNAME { get; set; }
    
        public virtual MVIEW__ADV_LOG MVIEW__ADV_LOG { get; set; }
        public virtual ICollection<MVIEW__ADV_ROLLUP> MVIEW__ADV_ROLLUP { get; set; }
        public virtual ICollection<MVIEW__ADV_ROLLUP> MVIEW__ADV_ROLLUP1 { get; set; }
    }
}
