//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_GC
    {
        public decimal GCID_ { get; set; }
        public decimal FJGID_ { get; set; }
        public decimal GCDESLEN { get; set; }
        public byte[] GCDES { get; set; }
        public decimal HASHVALUE { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
    
        public virtual MVIEW__ADV_FJG MVIEW__ADV_FJG { get; set; }
    }
}
