//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_AJG
    {
        public MVIEW__ADV_AJG()
        {
            this.MVIEW__ADV_FJG = new HashSet<MVIEW__ADV_FJG>();
        }
    
        public decimal AJGID_ { get; set; }
        public decimal RUNID_ { get; set; }
        public decimal AJGDESLEN { get; set; }
        public byte[] AJGDES { get; set; }
        public decimal HASHVALUE { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
    
        public virtual MVIEW__ADV_LOG MVIEW__ADV_LOG { get; set; }
        public virtual ICollection<MVIEW__ADV_FJG> MVIEW__ADV_FJG { get; set; }
    }
}
