//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_INDEX
    {
        public decimal RUNID_ { get; set; }
        public decimal RANK_ { get; set; }
        public decimal MVINDEX_ { get; set; }
        public Nullable<decimal> INDEX_TYPE { get; set; }
        public string INDEX_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string INDEX_CONTENT { get; set; }
        public string SUMMARY_OWNER { get; set; }
    }
}
