//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW__ADV_BASETABLE
    {
        public decimal COLLECTIONID_ { get; set; }
        public decimal QUERYID_ { get; set; }
        public string OWNER { get; set; }
        public string TABLE_NAME { get; set; }
        public Nullable<decimal> TABLE_TYPE { get; set; }
    
        public virtual MVIEW__ADV_WORKLOAD MVIEW__ADV_WORKLOAD { get; set; }
    }
}
