//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__PRIORITY_GROUP
    {
        public REPCAT__PRIORITY_GROUP()
        {
            this.REPCAT__PRIORITY = new HashSet<REPCAT__PRIORITY>();
        }
    
        public string SNAME { get; set; }
        public string PRIORITY_GROUP { get; set; }
        public decimal DATA_TYPE_ID { get; set; }
        public Nullable<decimal> FIXED_DATA_LENGTH { get; set; }
        public string PRIORITY_COMMENT { get; set; }
    
        public virtual ICollection<REPCAT__PRIORITY> REPCAT__PRIORITY { get; set; }
    }
}
