//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__FLAVORS
    {
        public decimal FLAVOR_ID { get; set; }
        public string GOWNER { get; set; }
        public string GNAME { get; set; }
        public string FNAME { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public string PUBLISHED { get; set; }
    
        public virtual REPCAT__REPCAT REPCAT__REPCAT { get; set; }
    }
}
