//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__TEMPLATE_SITES
    {
        public REPCAT__TEMPLATE_SITES()
        {
            this.REPCAT__SITE_OBJECTS = new HashSet<REPCAT__SITE_OBJECTS>();
        }
    
        public decimal TEMPLATE_SITE_ID { get; set; }
        public string REFRESH_TEMPLATE_NAME { get; set; }
        public string REFRESH_GROUP_NAME { get; set; }
        public string TEMPLATE_OWNER { get; set; }
        public string USER_NAME { get; set; }
        public string SITE_NAME { get; set; }
        public Nullable<decimal> REPAPI_SITE_ID { get; set; }
        public decimal STATUS { get; set; }
        public Nullable<decimal> REFRESH_TEMPLATE_ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public Nullable<System.DateTime> INSTANTIATION_DATE { get; set; }
    
        public virtual ICollection<REPCAT__SITE_OBJECTS> REPCAT__SITE_OBJECTS { get; set; }
    }
}
