//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__RESOLUTION_STATISTICS
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public decimal CONFLICT_TYPE_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
        public string METHOD_NAME { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string PRIORITY_GROUP { get; set; }
        public System.DateTime RESOLVED_DATE { get; set; }
        public string PRIMARY_KEY_VALUE { get; set; }
    }
}
