//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__TEMPLATE_PARMS
    {
        public REPCAT__TEMPLATE_PARMS()
        {
            this.REPCAT__USER_PARM_VALUES = new HashSet<REPCAT__USER_PARM_VALUES>();
            this.REPCAT__TEMPLATE_OBJECTS = new HashSet<REPCAT__TEMPLATE_OBJECTS>();
        }
    
        public decimal TEMPLATE_PARAMETER_ID { get; set; }
        public decimal REFRESH_TEMPLATE_ID { get; set; }
        public string PARAMETER_NAME { get; set; }
        public string DEFAULT_PARM_VALUE { get; set; }
        public string PROMPT_STRING { get; set; }
        public string USER_OVERRIDE { get; set; }
    
        public virtual REPCAT__REFRESH_TEMPLATES REPCAT__REFRESH_TEMPLATES { get; set; }
        public virtual ICollection<REPCAT__USER_PARM_VALUES> REPCAT__USER_PARM_VALUES { get; set; }
        public virtual ICollection<REPCAT__TEMPLATE_OBJECTS> REPCAT__TEMPLATE_OBJECTS { get; set; }
    }
}
