//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__REPCATLOG
    {
        public Nullable<decimal> VERSION { get; set; }
        public decimal ID { get; set; }
        public string SOURCE { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string ROLE { get; set; }
        public string MASTER { get; set; }
        public string SNAME { get; set; }
        public Nullable<decimal> REQUEST { get; set; }
        public string ONAME { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string A_COMMENT { get; set; }
        public string BOOL_ARG { get; set; }
        public string ANO_BOOL_ARG { get; set; }
        public Nullable<decimal> INT_ARG { get; set; }
        public Nullable<decimal> ANO_INT_ARG { get; set; }
        public Nullable<decimal> LINES { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<decimal> ERRNUM { get; set; }
        public string GNAME { get; set; }
    }
}
