//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__REPOBJECT
    {
        public REPCAT__REPOBJECT()
        {
            this.REPCAT__GENERATED = new HashSet<REPCAT__GENERATED>();
            this.REPCAT__GENERATED1 = new HashSet<REPCAT__GENERATED>();
            this.REPCAT__KEY_COLUMNS = new HashSet<REPCAT__KEY_COLUMNS>();
            this.REPCAT__REPCOLUMN = new HashSet<REPCAT__REPCOLUMN>();
            this.REPCAT__REPPROP = new HashSet<REPCAT__REPPROP>();
        }
    
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public decimal TYPE { get; set; }
        public Nullable<decimal> VERSION_ { get; set; }
        public byte[] HASHCODE { get; set; }
        public Nullable<decimal> ID { get; set; }
        public string OBJECT_COMMENT { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> GENPACKAGE { get; set; }
        public Nullable<decimal> GENPLOGID { get; set; }
        public Nullable<decimal> GENTRIGGER { get; set; }
        public Nullable<decimal> GENTLOGID { get; set; }
        public string GOWNER { get; set; }
        public string GNAME { get; set; }
        public byte[] FLAG { get; set; }
    
        public virtual ICollection<REPCAT__GENERATED> REPCAT__GENERATED { get; set; }
        public virtual ICollection<REPCAT__GENERATED> REPCAT__GENERATED1 { get; set; }
        public virtual ICollection<REPCAT__KEY_COLUMNS> REPCAT__KEY_COLUMNS { get; set; }
        public virtual REPCAT__REPCAT REPCAT__REPCAT { get; set; }
        public virtual ICollection<REPCAT__REPCOLUMN> REPCAT__REPCOLUMN { get; set; }
        public virtual ICollection<REPCAT__REPPROP> REPCAT__REPPROP { get; set; }
    }
}
