//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__REPSCHEMA
    {
        public string GOWNER { get; set; }
        public string SNAME { get; set; }
        public string DBLINK { get; set; }
        public string MASTERDEF { get; set; }
        public string SNAPMASTER { get; set; }
        public string MASTER_COMMENT { get; set; }
        public string MASTER { get; set; }
        public Nullable<decimal> PROP_UPDATES { get; set; }
        public string MY_DBLINK { get; set; }
        public Nullable<System.Guid> EXTENSION_ID { get; set; }
    
        public virtual DEF__DESTINATION DEF__DESTINATION { get; set; }
        public virtual REPCAT__REPCAT REPCAT__REPCAT { get; set; }
    }
}
