//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__INSTANTIATION_DDL
    {
        public decimal REFRESH_TEMPLATE_ID { get; set; }
        public string DDL_TEXT { get; set; }
        public decimal DDL_NUM { get; set; }
        public decimal PHASE { get; set; }
    
        public virtual REPCAT__REFRESH_TEMPLATES REPCAT__REFRESH_TEMPLATES { get; set; }
    }
}
