//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__PARAMETER_COLUMN
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public decimal CONFLICT_TYPE_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
        public decimal SEQUENCE_NO { get; set; }
        public string PARAMETER_TABLE_NAME { get; set; }
        public string PARAMETER_COLUMN_NAME { get; set; }
        public decimal PARAMETER_SEQUENCE_NO { get; set; }
        public decimal COLUMN_POS { get; set; }
        public Nullable<decimal> ATTRIBUTE_SEQUENCE_NO { get; set; }
    
        public virtual REPCAT__RESOLUTION REPCAT__RESOLUTION { get; set; }
    }
}
