//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__TEMPLATE_TARGETS
    {
        public decimal TEMPLATE_TARGET_ID { get; set; }
        public string TARGET_DATABASE { get; set; }
        public string TARGET_COMMENT { get; set; }
        public string CONNECT_STRING { get; set; }
        public string SPARE1 { get; set; }
    }
}
