//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__AUDIT_COLUMN
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string BASE_SNAME { get; set; }
        public string BASE_ONAME { get; set; }
        public decimal BASE_CONFLICT_TYPE_ID { get; set; }
        public string BASE_REFERENCE_NAME { get; set; }
        public string ATTRIBUTE { get; set; }
    
        public virtual REPCAT__AUDIT_ATTRIBUTE REPCAT__AUDIT_ATTRIBUTE { get; set; }
        public virtual REPCAT__CONFLICT REPCAT__CONFLICT { get; set; }
    }
}
