//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__RESOL_STATS_CONTROL
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public System.DateTime CREATED { get; set; }
        public decimal STATUS { get; set; }
        public System.DateTime STATUS_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> PURGED_DATE { get; set; }
        public Nullable<System.DateTime> LAST_PURGE_START_DATE { get; set; }
        public Nullable<System.DateTime> LAST_PURGE_END_DATE { get; set; }
    }
}
