//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__TEMPLATE_TYPES
    {
        public REPCAT__TEMPLATE_TYPES()
        {
            this.REPCAT__REFRESH_TEMPLATES = new HashSet<REPCAT__REFRESH_TEMPLATES>();
        }
    
        public decimal TEMPLATE_TYPE_ID { get; set; }
        public string TEMPLATE_DESCRIPTION { get; set; }
        public byte[] FLAGS { get; set; }
        public string SPARE1 { get; set; }
    
        public virtual ICollection<REPCAT__REFRESH_TEMPLATES> REPCAT__REFRESH_TEMPLATES { get; set; }
    }
}
