//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__GENERATED
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public decimal TYPE { get; set; }
        public Nullable<decimal> REASON { get; set; }
        public string BASE_SNAME { get; set; }
        public string BASE_ONAME { get; set; }
        public decimal BASE_TYPE { get; set; }
        public string PACKAGE_PREFIX { get; set; }
        public string PROCEDURE_PREFIX { get; set; }
        public string DISTRIBUTED { get; set; }
    
        public virtual REPCAT__REPOBJECT REPCAT__REPOBJECT { get; set; }
        public virtual REPCAT__REPOBJECT REPCAT__REPOBJECT1 { get; set; }
    }
}
