//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__REPCOLUMN
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public decimal TYPE { get; set; }
        public string CNAME { get; set; }
        public string LCNAME { get; set; }
        public Nullable<System.Guid> TOID { get; set; }
        public Nullable<decimal> VERSION_ { get; set; }
        public byte[] HASHCODE { get; set; }
        public string CTYPE_NAME { get; set; }
        public string CTYPE_OWNER { get; set; }
        public Nullable<decimal> ID { get; set; }
        public Nullable<decimal> POS { get; set; }
        public string TOP { get; set; }
        public byte[] FLAG { get; set; }
        public Nullable<decimal> CTYPE { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> PRECISION_ { get; set; }
        public Nullable<decimal> SCALE { get; set; }
        public Nullable<decimal> NULL_ { get; set; }
        public Nullable<decimal> CHARSETID { get; set; }
        public Nullable<decimal> CHARSETFORM { get; set; }
        public byte[] PROPERTY { get; set; }
        public Nullable<decimal> CLENGTH { get; set; }
    
        public virtual REPCAT__REPOBJECT REPCAT__REPOBJECT { get; set; }
    }
}
