//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__GROUPED_COLUMN
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public decimal POS { get; set; }
    
        public virtual REPCAT__COLUMN_GROUP REPCAT__COLUMN_GROUP { get; set; }
    }
}
