//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__REPPROP
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public decimal TYPE { get; set; }
        public string DBLINK { get; set; }
        public Nullable<decimal> HOW { get; set; }
        public string PROPAGATE_COMMENT { get; set; }
        public Nullable<decimal> DELIVERY_ORDER { get; set; }
        public Nullable<decimal> RECIPIENT_KEY { get; set; }
        public Nullable<System.Guid> EXTENSION_ID { get; set; }
    
        public virtual REPCAT__REPOBJECT REPCAT__REPOBJECT { get; set; }
    }
}
