//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__CONFLICT
    {
        public REPCAT__CONFLICT()
        {
            this.REPCAT__AUDIT_COLUMN = new HashSet<REPCAT__AUDIT_COLUMN>();
            this.REPCAT__RESOLUTION = new HashSet<REPCAT__RESOLUTION>();
        }
    
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public decimal CONFLICT_TYPE_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
    
        public virtual ICollection<REPCAT__AUDIT_COLUMN> REPCAT__AUDIT_COLUMN { get; set; }
        public virtual ICollection<REPCAT__RESOLUTION> REPCAT__RESOLUTION { get; set; }
    }
}
