//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__EXCEPTIONS
    {
        public decimal EXCEPTION_ID { get; set; }
        public string USER_NAME { get; set; }
        public string REQUEST { get; set; }
        public Nullable<decimal> JOB { get; set; }
        public Nullable<System.DateTime> ERROR_DATE { get; set; }
        public Nullable<decimal> ERROR_NUMBER { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public Nullable<decimal> LINE_NUMBER { get; set; }
    }
}
