//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__KEY_COLUMNS
    {
        public string SNAME { get; set; }
        public string ONAME { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string COL { get; set; }
    
        public virtual REPCAT__REPOBJECT REPCAT__REPOBJECT { get; set; }
    }
}
