//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__REFRESH_TEMPLATES
    {
        public REPCAT__REFRESH_TEMPLATES()
        {
            this.REPCAT__INSTANTIATION_DDL = new HashSet<REPCAT__INSTANTIATION_DDL>();
            this.REPCAT__TEMPLATE_OBJECTS = new HashSet<REPCAT__TEMPLATE_OBJECTS>();
            this.REPCAT__TEMPLATE_PARMS = new HashSet<REPCAT__TEMPLATE_PARMS>();
            this.REPCAT__TEMPLATE_REFGROUPS = new HashSet<REPCAT__TEMPLATE_REFGROUPS>();
            this.REPCAT__USER_AUTHORIZATIONS = new HashSet<REPCAT__USER_AUTHORIZATIONS>();
        }
    
        public decimal REFRESH_TEMPLATE_ID { get; set; }
        public string OWNER { get; set; }
        public string REFRESH_GROUP_NAME { get; set; }
        public string REFRESH_TEMPLATE_NAME { get; set; }
        public string TEMPLATE_COMMENT { get; set; }
        public string PUBLIC_TEMPLATE { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public Nullable<decimal> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public decimal REFRESH_GROUP_ID { get; set; }
        public decimal TEMPLATE_TYPE_ID { get; set; }
        public decimal TEMPLATE_STATUS_ID { get; set; }
        public byte[] FLAGS { get; set; }
        public string SPARE1 { get; set; }
    
        public virtual ICollection<REPCAT__INSTANTIATION_DDL> REPCAT__INSTANTIATION_DDL { get; set; }
        public virtual REPCAT__TEMPLATE_TYPES REPCAT__TEMPLATE_TYPES { get; set; }
        public virtual REPCAT__TEMPLATE_STATUS REPCAT__TEMPLATE_STATUS { get; set; }
        public virtual ICollection<REPCAT__TEMPLATE_OBJECTS> REPCAT__TEMPLATE_OBJECTS { get; set; }
        public virtual ICollection<REPCAT__TEMPLATE_PARMS> REPCAT__TEMPLATE_PARMS { get; set; }
        public virtual ICollection<REPCAT__TEMPLATE_REFGROUPS> REPCAT__TEMPLATE_REFGROUPS { get; set; }
        public virtual ICollection<REPCAT__USER_AUTHORIZATIONS> REPCAT__USER_AUTHORIZATIONS { get; set; }
    }
}
