//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__REPGROUP_PRIVS
    {
        public Nullable<decimal> USERID { get; set; }
        public string USERNAME { get; set; }
        public string GOWNER { get; set; }
        public string GNAME { get; set; }
        public decimal GLOBAL_FLAG { get; set; }
        public System.DateTime CREATED { get; set; }
        public Nullable<decimal> PRIVILEGE { get; set; }
    
        public virtual REPCAT__REPCAT REPCAT__REPCAT { get; set; }
    }
}
