//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__PRIORITY
    {
        public string SNAME { get; set; }
        public string PRIORITY_GROUP { get; set; }
        public decimal PRIORITY { get; set; }
        public byte[] RAW_VALUE { get; set; }
        public string CHAR_VALUE { get; set; }
        public Nullable<decimal> NUMBER_VALUE { get; set; }
        public Nullable<System.DateTime> DATE_VALUE { get; set; }
        public string VARCHAR2_VALUE { get; set; }
        public string NCHAR_VALUE { get; set; }
        public string NVARCHAR2_VALUE { get; set; }
        public string LARGE_CHAR_VALUE { get; set; }
    
        public virtual REPCAT__PRIORITY_GROUP REPCAT__PRIORITY_GROUP { get; set; }
    }
}
