//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__OBJECT_TYPES
    {
        public REPCAT__OBJECT_TYPES()
        {
            this.REPCAT__SITE_OBJECTS = new HashSet<REPCAT__SITE_OBJECTS>();
            this.REPCAT__TEMPLATE_OBJECTS = new HashSet<REPCAT__TEMPLATE_OBJECTS>();
        }
    
        public decimal OBJECT_TYPE_ID { get; set; }
        public string OBJECT_TYPE_NAME { get; set; }
        public byte[] FLAGS { get; set; }
        public string SPARE1 { get; set; }
    
        public virtual ICollection<REPCAT__SITE_OBJECTS> REPCAT__SITE_OBJECTS { get; set; }
        public virtual ICollection<REPCAT__TEMPLATE_OBJECTS> REPCAT__TEMPLATE_OBJECTS { get; set; }
    }
}
