//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPCAT__AUDIT_ATTRIBUTE
    {
        public REPCAT__AUDIT_ATTRIBUTE()
        {
            this.REPCAT__AUDIT_COLUMN = new HashSet<REPCAT__AUDIT_COLUMN>();
        }
    
        public string ATTRIBUTE { get; set; }
        public decimal DATA_TYPE_ID { get; set; }
        public Nullable<decimal> DATA_LENGTH { get; set; }
        public string SOURCE { get; set; }
    
        public virtual ICollection<REPCAT__AUDIT_COLUMN> REPCAT__AUDIT_COLUMN { get; set; }
    }
}
