//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLPLUS_PRODUCT_PROFILE
    {
        public string PRODUCT { get; set; }
        public string USERID { get; set; }
        public string ATTRIBUTE { get; set; }
        public string SCOPE { get; set; }
        public Nullable<decimal> NUMERIC_VALUE { get; set; }
        public string CHAR_VALUE { get; set; }
        public Nullable<System.DateTime> DATE_VALUE { get; set; }
        public string LONG_VALUE { get; set; }
    }
}
